---
title: "facets"
format: revealjs
editor: visual
---


## Facet wrap {auto-animate=true}

```{r, echo=TRUE, warning=FALSE, message=FALSE}
ggplot(data = penguins,
       aes(x = body_mass_g, y = bill_length_mm, colour = species)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~species) # Can take one or two columns
```

## Facet grid {auto-animate=true}

```{r, echo=TRUE, warning=FALSE, message=FALSE}
ggplot(data = penguins,
       aes(x = body_mass_g, y = bill_length_mm, colour = species)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_grid(island~species) # Takes two or more columns
```

## Change labels {auto-animate=true}

```{r, echo=TRUE, warning=FALSE, message=FALSE}
ggplot(data = penguins,
       aes(x = body_mass_g, y = bill_length_mm, colour = species)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_grid(island~species) +
  labs(x = "Body mass (g)", y = "Bill length (mm)", colour = "Species") + # Change labels
  theme(legend.position = "bottom") # Change legend position
```

## More than dot plots

* There are many built-in **`ggplot2`** figures
* There are also many ways to connect them together